pkg:core:
- packages/processor/**/*

pkg:rollup:
- packages/rollup/**/*

pkg:rollup-rewriter:
- packages/rollup-rewriter/**/*

pkg:svelte:
- packages/svelte/**/*

pkg:webpack:
- packages/webpack/**/*

pkg:browserify:
- packages/browserify/**/*

pkg:cli:
- packages/cli/**/*

pkg:www:
- packages/www/**/*

greenkeeper:
- packages/processor/**/*
